- README.md
- lua/telescope/_extensions/zk.lua
- lua/telescope/zk/util.lua
- lua/zk.lua
- lua/zk/api.lua
- lua/zk/config.lua
- lua/zk/lsp.lua
- lua/zk/util.lua
It's now possible to have inline queries like so:
*VimL*
```vim
:ZkList { createdAfter = "3 days ago", tags = { "work" } }
" or directly via Telescope, but functionality is limited in VimL
:Telescope zk notes createdAfter=3\ days\ ago
```
*Lua*
```lua
require("zk").list(nil, { createdAfter = "3 days ago", tags = { "work" } })
-- or directly via Telescope
require('telescope').extensions.zk.notes({ createdAfter = "3 days ago", tags = { "work" } })
```
Also many documentation updates, both in the code and in the README.
> inline queries and documentation updates

- README.md
- lua/zk.lua
- lua/zk/api.lua
- lua/zk/util.lua
There is a new `ZkNewLink` command. Select some text in visual mode, and then execute
```viml
:'<,'>ZkNewLink
```
this will create a new note and use the last visual selection as the title while replacing the selection with a link to the new note.
You can also pass the usual options
```viml
:'<,'>ZkNewLink { edit = false, dir = "work", date = "yesterday" }
```
---
```viml
:ZkNew daily
```
becomes
```viml
:ZkNew { dir = "daily" }
```
which is a bit more verbose, but is consistent with `:ZkList` and allows for something like
```viml
:ZkNew { dir = "daily", date = "yesterday" }
```
> Make :ZkNew and :ZkIndex consistent with :ZkList

- README.md
Clarify the key mappings example, including the basic LSP ones.
See https://github.com/mickael-menu/zk-nvim/discussions/17
> Improve key mappings example

- README.md
- doc/zk.txt
- lua/zk.lua
- lua/zk/api.lua
Errors can for example happen when no `zk` notebook root is found. The `zk.api` level is the wrong place to consume these errors.
> Don't swallow LSP errors in zk.api

- lua/zk/pickers/fzf.lua
The space of `delimiter` in `fzf.lua` cause note with spaces in filename
not openable.
Picker: `fzf`
Example note (zsh.config - vi mode.md):
```
note body...
```
> fzf: fix jumping to note with spaces in filename

- lua/zk/pickers/telescope.lua
It's caused by preview of empty note content
Picker: telescope
Fix https://github.com/mickael-menu/zk-nvim/issues/44
> fix(#44): 's: expected string, got nil' on :ZkNotes

- lua/zk/pickers/fzf.lua
In tag list in `fzf` the line format is `notes_count delimiter tag_name` (e. g. `3 sometag`). Incorrect regexp is used for parsing tag name from the selected line. It causes that the selected tag is empty and notes are not filtered by tag in the following notes list. This pull request should fix it.
> fix tag name selection in fzf

- lua/zk/pickers/telescope.lua
What are your thoughts on this "optimization"?
Prior to this change, the `rawContents` of **all** notes were loaded via the LSP connection.  When the quantity of notes is large (30k), this results in more memory utilization as well as slower transfer times from the LSP server, which ultimately delays the opening of Telescope.
With this change, `rawContents` is no longer requested from the LSP server--only `title`, `absPath`, and `path` are loaded for each note. To generate previews, we use the "absPath" to open the file via the `buffer_previewer_maker` when Telescope needs to show a preview.
I tested the performance of this against 30,000 random notes of lorem ipsum with a median size of 1,464 bytes.  Memory utilization is much lower and the time to open the Telescope window is roughly …
> Lazily load note contents in Telescope

- lua/zk/commands/builtin.lua
- lua/zk/util.lua
I made a conversion bytes based indexes of character position to char based before execute `zk.new` command. So now I can successfully extract titles from Cyrillic encoded text.
> fix selection of non ascii title

- README.md
- lua/zk.lua
- lua/zk/commands/builtin.lua
- lua/zk/util.lua
Add a new `inline = true` option to `ZkNew`, `ZkNewFromTitleSelection` and `ZkNewFromContentSelection` to insert the generated note content at the caret position, instead of writing the new note to the file system.
Under the hood, it uses the new `zk.new` options `dryRun` and `insertContentAtLocation` from https://github.com/mickael-menu/zk/pull/276.
> Allow to inline new notes in the current buffer

- lua/zk/lsp.lua
Hi @mickael-menu,
I have prepared a solution for #104 and more generally a situation when zk lsp is set up outside `zk-nvim` (e.g. through lsp config).
The reason for going this route is connected with the builtin `zk lsp` setup seems to be broken for Windows (that I know is not supported officially). I think that because of improper path handling the root_dir is not found. [`lsp config`](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/zk.lua#L7) is using their own util function to find a dir with .zk directory, that seems to do the trick.
I think that having an option to use externally started server is still a feature worth to have. In case multiple zk-lsp servers are started and successfully attached to any buffer, the first one found by name is …
> Use already attached externally setup lsp client if available

- lua/zk.lua
this fix error when not use `picker_options` parameter
> fix: `require("zk").edit` error

- README.md
- lua/zk/commands/init.lua
Removed user command helpers, as `nvim_create_user_command` and `nvim_del_user_command` are officially released.
Fix #114
> fix(commands): remove user command creation and deletion wrappers

- lua/zk/root_pattern_util.lua
This is copied from `lua/lspconfig/util.lua` in nvim-lspconfig.
The root_pattern lookup will fail when the path contains certain special characters.
Fixes the issue discussed in [#2111](https://github.com/neovim/nvim-lspconfig/issues/2111)
> fix: escape special characters in path

- lua/zk/commands/builtin.lua
- lua/zk/pickers/fzf_lua.lua
Hi!
I moved to use [fzf-lua](https://github.com/ibhagwan/fzf-lua) and have been working these days to be able to use it with zk-nvim. While you are already supporting `fzf`, fzf-lua adds some nice goodies and this picker makes finding notes more consistent if you are a user of the plugin.
The small drawback is that is not very configurable right now, since `picker_options` is not exposed to be used with built-in commands, and this does not implement an extension like with telescope, so the picker can't be configured from `fzf-lua` options either. For that reason I've added some default actions that I think are handy, like opening selections in splits or tabs. If `picker_options` can be exposed at a later time, I can change this so people can configure mappings and other options …
> Added support for fzf-lua as a picker

- lua/zk.lua
Using Lazy for packaging management, if `zk-nvim` is configured to be lazy loaded at some point after the current buffer's filetype is set, the current buffer wouldn't be attached to the lsp server.
For example, if I configure `zk-nvim` this way:
```
{
"mickael-menu/zk-nvim",
cmd = "ZkInsertLink",
config = function()
require("zk").setup {
picker = "telescope"
}
end
}
```
Therefore using the execution of `:ZkInsertLink` as a trigger for lazy loading of `zk-nvim`, the current buffer, should it be a markdown file of interest, is not attached. I'd need to manually attach it.
> attach current buffer once before creating autocmd for lazy loading

- README.md
- doc/zk.txt
I noticed the earlier pull [https://github.com/mickael-menu/zk-nvim/pull/138](https://github.com/mickael-menu/zk-nvim/pull/138) added support for fzf-lua as a picker but it is not documented yet. I only found out about it by checking the source.
Changed a couple lines on the docs and README to document it.
Hope this helps, thanks!
> Documentation for fzf_lua support

- README.md
Tone and information already approved by Mickaël in zk PR [376](https://github.com/zk-org/zk/pull/376).
@kabouzeid , requested your review as I wanted to include your contributions in the message. Let me know how it sits and/or edit / remove at your own free will 👍
> readme: notify of maintenance mode

- README.md
- doc/zk.txt
- lua/zk/pickers/minipick.lua
With [mini](https://github.com/echasnovski/mini.nvim/tree/main) gaining in popularity, this commit adds support for [mini.pick](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-pick.md).
Here is a short screencast showing this new picker in action with Zk notes:
https://github.com/zk-org/zk-nvim/assets/747855/cf645482-c3eb-4713-8925-bb1501f54cb8
> Add support for `mini.pick` as a picker

- doc/zk.txt
Without this modeline, when I run `:help zk-zk-nvim`, the filetype is
txt (text), not help.
> fix(doc): add vim modeline to properly show the help

- README.md
- lua/zk/lsp.lua
resolves #165.
lsp nvim <=0.9 -> 0.10: `get_active_clients` -> `get_clients`.
> support nvim v0.10.0 lsp api change (get_clients)

- lua/zk.lua
- lua/zk/pickers/fzf_lua.lua
- lua/zk/ui.lua
- selene.toml
- stylua.toml
During #171 I noticed that the call_parenthesis stylua setting had not been set in `stylua.toml`. 
Updated the stylua.toml file accordingly in keeping with the current formatting in the project and formatted the whole project.
I added a line length of 110 as a sane default (and personal preference). 
It's fairly arguable to have some hard setting for line length to catch future contributions with line wrap on?..
> enforce current stylua style

- lua/zk/commands/builtin.lua
- lua/zk/util.lua
The previous implementation would only copy the first byte of the last
character. This is never correct, and produces an invalid sequence.
See: https://github.com/zk-org/zk-nvim/issues/179
> Fix get_text_in_range when the last character is multibyte

- lua/zk/pickers/fzf_lua.lua
Hello, as a user I wish to cancel/abort the tag view before showing notes in the case I picked a wrong tag or simply was not interested to see notes anymore. ESC or any your binding to cancel an fzf action is not working, as it is not fallen under the default fzf action. This small MR addresses this issue.
> Fix unable to abort or cancel show_tag_picker on fzf_lua issue

- lua/zk/root_pattern_util.lua
The nightly Neovim is warning that tbl_flatten has been deprecated and should be replaced with what I have put in this commit.
> Update to new form of tbl_flatten to fix deprecation warnings

- README.md
- lua/zk/commands/builtin.lua
- lua/zk/util.lua
Shows all active note buffers in your picker of choice.
Run `:ZkBuffers`
The underlying call is the same as `ZkNotes` and therefore accepts the same options, as listed [here in the docs](https://github.com/zk-org/zk/blob/main/docs/tips/editors-integration.md#zklist).
> feat: ZkBuffers

- README.md
- doc/zk.txt
- lua/zk/ui.lua
**Title:** 
Add support to set default configurations for pickers
**Description:**
Hi there, I've been using the plugin recently, and it's been great! However, I prefer using the Ivy format with Telescope. To allow users more flexibility in customizing their picker, I’ve added support for passing down picker options from the configuration.
This was made in consideration of the other pickers too, users can define default configurations for `fzf_options`, `snacks_picker` and ect.
Here is an example of how this would be used:
```lua
require("zk").setup({
picker = "telescope",
picker_options = {
telescope = {
layout_strategy = "bottom_pane",
sorting_strategy = "ascending",
layout_config = {
height = 25,
},
border = true,
borderchars = {
prompt = { "─", " ", " ", " ", "─", "─", " ", " " }, …
```
> Added the ability to pass down default options to pickers

- README.md
It seems like there's a missing newline after the Important block for the README.
> Fix README Important Block

- lua/zk/util.lua
When creating a note from title selection with `ZkNewFromTitleSelection`, I keep getting this warning:
```lua
position_encoding param is required in vim.lsp.util.make_given_range_params. Defaulting to position encoding of the first client.
```
It can be fixed by passing the encoding explicitly. For zk, this seems to be utf-16 (`:lua= vim.lsp.get_clients({ name = "zk" })[1].offset_encoding`).
This PR fixes the issue by 1) finding the zk client and 2) setting the encoding to what the zk client returns, or to utf-16 if no zk client is found (but with an error message in the latter case).
I'm not sure if the whole encoding detection part is necessary. Could we just hardcode "utf-16" as an argument to `make_given_range_params` directly or could this change depending on ZK installations? …
> Fix position encoding parameter warning when creating note from selection

- lua/zk/util.lua
Reverts zk-org/zk-nvim#221
Seems I didn't test properly. This broke `ZkNewFromTitleSelection` completely for me.
Needs another look at.
zk 0.15.1-1-g6fc9b01
NVIM v0.10.2
> Revert "Fix position encoding parameter warning when creating note from selection"

- README.md
- lua/zk.lua
- lua/zk/config.lua
- lua/zk/lsp.lua
- lua/zk/root_pattern_util.lua
- lua/zk/util.lua
Resolves #228 
Other pr's addressing this issue: #223 #229 
(If this works) then the issue was mainly to do with a buggy change over from `vim.tbl_flatten` to [`iter:flatten`](https://neovim.io/doc/user/lua.html#Iter%3Aflatten())
This was killing the root_pattern_util functionality, and therefore not returning a notebook root, that the lsp could hook into -- which meant no client_id was being returned in any case as `zk` always wants (and needs) to find a notebook root.
> [!note]
> This is only compatible with neovim 0.11.*
This branch can be tested live by:
```lua
return {
'zk-org/zk-nvim',
branch = 'fix/client-nil-error',
config = function()
require('zk').setup()
end,
}
```
Currently, something is stopping the lsp attaching, [see …
> fix client_id expected number got nil

- lua/zk/pickers/fzf_lua.lua
This makes it possible to create a new note from the note pickers. Currently only implemented for fzf_lua because that is what I use.
If this patch doesn't get merged, here is an example to get this behavior from your own config.
```lua
local zk = require("zk")
local ansi_codes = require("fzf-lua").utils.ansi_codes
local opts = function(tbl)
return vim.tbl_extend("keep", { buffer = 0, silent = true }, tbl)
end
vim.keymap.set("n", "<space>zf", function()
zk.edit({ sort = { "modified" } }, {
fzf_lua = {
fzf_opts = {
["--header"] = ansi_codes.blue("CTRL-E: create a note with the query as title"),
},
actions = {
["ctrl-e"] = function()
local query = require("fzf-lua").config.__resume_data.last_query
require("zk").new { title = query }
end,
},
},
})
end, opts { desc = "Find notes" })
``` …
> feat: create new note from fzf_lua notes picker

- lua/zk/config.lua
Resolves #248 and #242 
zk-nvim version v0.4.1 attempted to handle changes to the neovim lsp API. These changes to zk-nvim introduced a bug where two zk lsp clients could appear if:
- the user opens neovim fresh, and then uses `:Zk..` commands to edit/create a note.
This PR fixes this. It would seem the issue was that the `root_marker` in `vim.lsp.config` is not used by neovim lsp to determine whether an existing lsp should be reattached to the new buffer or not:
```
start({config}, {opts})                                      *vim.lsp.start()*
Create a new LSP client and start a language server or reuses an already
running client if one is found matching `name` and `root_dir`. Attaches
the current buffer to the client.
Example: >lua
vim.lsp.start({
name = 'my-server-name',
cmd = …
```
> fix lsp-attach / double lsp client issue

- lua/zk/config.lua
Reverts zk-org/zk-nvim#251
`root_dir` does not allow for executing `:Zk` commands when outside a notebook root...
> Revert "fix lsp-attach / double lsp client issue"
